spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devpub
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_LOGIN}
    password: ${PASSWORD_APP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true