# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env: 
  MAVEN_CLEAN: ${{ vars.MAVEN_CLEAN }}
  MAVEN_PACKAGE: ${{ vars.MAVEN_PACKAGE }}
  SECRET_WORD: ${{ secrets.SECRET_WORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Start
      run: echo "start maven build"
    - name: Test env
      run: echo $MAVEN_CLEAN $MAVEN_PACKAGE
    - name: Build with Maven
      run: mvn -B $MAVEN_CLEAN $MAVEN_PACKAGE --file $SECRET_WORD
    - name: Secret test
      run: echo "we use $SECRET_WORD"  

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
